### ISSUE TITLE
Plugin Intake Checklist 

### ISSUE THREAD

**Issue by jfrerich** [mattermost-community/mattermost-plugin-circleci#67]
### Mark as done after each step completed

As the individual doing plugin intake, you will need the following privileges.

- Github repository admin access.  You will see the `Settings` option tab if access has been granted. (next to Pull requests, Actions, Releases)
- Mattermost Channel admin access.  This will allow editing the channel header

The following options require Mattermost admin privileges.  If you don't have these (likely) ask management

- Mattermost sysadmin access.
  - Needed for creating new public channels
  - Needed for `/jira subscribe` if applicable

## How To Transfer Repo to the Mattermost Org
- Transfer the repo to a member with Mattermost GitHub Organization admin access
- They will need to then transfer from their personal account to the Mattermost Organization
- Ask them to add you as repo admin to finish the intake process

## Repository Setup - Settings

- [ ] **Options (Make sure the following are the only selected items)**
  - **Features**:
  - Wikis
  - Restrict editing to users in teams with push access only
  - Issues
    - Projects
  - **Data services**
  - Security alerts
  - **Merge Button**:
  - Allow squash merging
  - Automatically delete head branches

- [ ] **Setup GitHub 1st Project**

  - `Projects` > `New Project`
  - **Board Name:** v1.0
  - **Description:** First shippable version, to be submitted to the plugin marketplace.
  - **Add Columns:** Use https://github.com/mattermost/mattermost-plugin-solar-lottery/projects/1 as a template

- [ ] **Collaborators (Manage Access)**

  - Add the following
    - mattermost/core-build-engineers
    - mattermost/core-committers
    - mattermost/core-developers
    - mattermost/core-pms
    - mattermost/integrations
    - mattermost/qa-core-team
    - mattermost/tech-writers

- [ ] **Branches**

Branch protection Rules: master should already be available. Click edit next to master and verify the following defaults

- **Branch name pattern: `master`**
  - Applies to 1 branch: `master`
- **Protecting matching branches**
- Require pull request reviews before merging: required approving reviews :2
  - Dismiss stale pull request approvals when new commits are pushed
- Require review from Code Owners
- Require status checks to pass before merging

- [ ] **Webhooks**

  - [ ] Add [codecov.io](http://codecov.io), create the webhook from codecove.io/gh/mattermost/mattermost-plugin-<name>
    - `Settings` > `General` > `GitHub Webhook` > `Create new webhook`
    - This will add the webhook to GH.  View in `GH` > `Settings` > `Webhooks`
  - [ ] CircleCI
  - login into https://circleci.com/gh/mattermost > `Add Projects` > search for plugin repo > `Set Up Project` > `Start Building`
  - `Project Settings` > `Advanced` > `Build forked pull requests` (allows circleci to run on forked repos)
  - [ ] copy https://github.com/mattermost/mattermost-plugin-demo/blob/master/.circleci/config.yml into local plugin repo (No edits needed)
  - [ ] Submit as PR
    - Title: Update CircleCi
    - Description: Sync to latest https://github.com/mattermost/mattermost-plugin-demo/blob/master/.circleci/config.yml
  - Add to CircleCI from circleCI (adds the webhook and deploy key)
  - [ ] Mattermod
  - Payload URL: https://mattermod.mattermost.com/pr_event
  - Content Type: `application/json`
  - Secret: ??  Where to get secret?
  - Which events to trigger webhook?
    - Let me select individual events
      - `Issue Comments`
      - `Issues`
      - `Pull requests`
      - `Select Active`

### Install GitHub Apps

- [ ] CircleCi Checks
- [ ] Dependabot Preview

## README.md

- [ ] add circleci badge
- [ ] add codecov badge
- [ ] add go report badge

If these don't exist, create Tickets for each (these are available in the Demo page)

- [ ] Add HW to Readme
- [ ] Slash commands documented
- [ ] Images added
- [ ] Installation / Configuration section added

## Repository checks

Each of the following might require new commits and PRs against master.

- [ ] `go mod tidy`
- [ ] version
- [ ] All tests passing
- [ ] `npm audit fix`
- [ ] `npm-check -E -u` to view the changes interactively
- [ ] `npm-check -E -y` to update without interactive
  - check in `package-lock.json` and `package.json`
- [ ] grep for original repo references in all files

## Mattermost Channels Setup

- [ ] `Plugin: <plugin_name>` - setup new plugin channel
  - [ ] Add plugin author and some other integration team members
  - [ ] Github subscribe
    - `/github subscribe mattermost/mattermost-plugin-solar-lottery pulls,issues,creates`
  - [ ] Header: [HW] | [repo] | [circle-ci] | PM: <name> | Dev: <name>

```

Actual text for header - replace all instances of <plugin_repo>, <pm-name>, <dev-name>

[GitHub](https://github.com/mattermost/<plugin_repo>) | [Help Wanted](https://github.com/mattermost/<plugin_repo>/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22up+for+grabs%22+label%3A%22help+wanted%22+sort%3Aupdated-desc) | [![CircleCI](https://circleci.com/gh/mattermost/<plugin-repo-namme>.svg?style=shield)](https://circleci.com/gh/mattermost/<plugin-repo) | PM: @<pm-name> | Dev: @<dev-name>
```

- [ ] GitHub subscribe in ~Plugin Heartbeat channel
  - `/github subscribe mattermost/mattermost-plugin-solar-lottery pulls`

## The Rest

- [ ] Labels: add to [mapping.go#L7](https://github.com/mattermost/mattermost-utilities/blob/master/labels/mapping.go#L7) and cd labels && go run . -default -v
- [ ] Add to tracking spreadsheet, https://docs.google.com/spreadsheets/d/1jPuvFdeaWJy_-faP-p71_x66OC4x6Udp8vrasrJzbEo/edit#gid=1550130552
- [ ] Add to pinned issue links in https://github.com/mattermost/mattermost-server/issues/12656
  - [ ] add repo to `Good First Issue` link (listed alphabetically)
  - [ ] add repo to `Up For Grabs - Golang` link (listed alphabetically)
  - [ ] add repo to `All Plugin Up For Grabs` link (listed alphabetically)
  - [ ] add repo full list of repositories

**Comment by nathanaelhoun** [comment]
Hi @jfrerich or @metanerd :-)

Can an admin of the repo change the required checks to merge to remove the current three ones, and replace them by the latest?

If you can also disable Github Pages on the repo, it's wonderful!

Thanks in advance :smile: 

![image](https://user-images.githubusercontent.com/45119518/110177585-7a7ed200-7e05-11eb-9947-0e90b369c85d.png)
